spring.application.name=scrimlogic
server.port=8082
spring.threads.virtual.enabled=true

# Configuração da pasta de simulação
scrimlogic.inbox.path=./inbox

spring.datasource.url=jdbc:postgresql://localhost:5433/scrimlogic
spring.datasource.username=admin
spring.datasource.password=admin_password

spring.jpa.hibernate.ddl-auto=update

#Batch size para não sobrecarregar o DB
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true